### ISSUE TITLE
Cannot use $payrollAUPaySlip->addEarningsLine(....) when no extant earnings lines

### ISSUE THREAD

**Issue by Healyhatman** [calcinai/xero-php#718] opened 2020-04-08 06:30 UTC
If I retrieve a PaySlip from Xero, and it does not include any EarningsLines, I cannot use ->addEarningsLine. 

I am able to add an EarningsLine if one already exists on the payslip. 
I am able to add an EarningsLine if I am creating a payslip.

```
"message": "Undefined property XeroPHP\\Remote\\Model::$.\n",
    "exception": "ErrorException",
    "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\calcinai\\xero-php\\src\\XeroPHP\\Remote\\Model.php",
    "line": 508,
    "trace": [
        {
            "function": "handleError",
            "class": "Illuminate\\Foundation\\Bootstrap\\HandleExceptions",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\calcinai\\xero-php\\src\\XeroPHP\\Remote\\Model.php",
            "line": 508,
            "function": "trigger_error"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\calcinai\\xero-php\\src\\XeroPHP\\Remote\\Model.php",
            "line": 579,
            "function": "__set",
            "class": "XeroPHP\\Remote\\Model",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\vendor\\calcinai\\xero-php\\src\\XeroPHP\\Models\\PayrollAU\\Payslip.php",
            "line": 318,
            "function": "offsetSet",
            "class": "XeroPHP\\Remote\\Model",
            "type": "->"
        },
        {
            "file": "C:\\inetpub\\wwwroot\\caremaster\\app\\Http\\Controllers\\Xero\\XeroPayRunController.php",
            "line": 292,
            "function": "addEarningsLine",
            "class": "XeroPHP\\Models\\PayrollAU\\Payslip",
            "type": "->"
        },
```

**Comment by Josh-G** [comment] 2020-04-08 10:50
I can reproduce this issue. I have [created a fix](https://github.com/calcinai/xero-php/compare/master...SynergiTech:handle-empty-relations), however I'm not clear exactly how this 
will affect hydrating other models (@calcinai any insight?). 
@Healyhatman Do you want to try my branch and see if you can spot any regressions?

Xero returns an empty node in the XML:
```xml
<EarningsLines />
```
which gets coerced to an empty string `''`,
https://github.com/calcinai/xero-php/blob/7fb80f5785e524b53011b7783894ded02eeccbe5/src/XeroPHP/Helpers.php#L83
which fails this check
https://github.com/calcinai/xero-php/blob/7fb80f5785e524b53011b7783894ded02eeccbe5/src/XeroPHP/Remote/Model.php#L211

which then casts this property from the empty string
https://github.com/calcinai/xero-php/blob/7fb80f5785e524b53011b7783894ded02eeccbe5/src/XeroPHP/Remote/Model.php#L224-L229

creating an empty `EarningsLine` and assigning it to the property instead of the `Remote\Collection` which is needed.

It looks like this bug would affect any property that is expected to be an array and is returned as empty in the XML.

```
  'EarningsLines' => 
    object(XeroPHP\Models\PayrollAU\Payslip\EarningsLine)[44]
      protected '_data' => 
        array (size=4)
          'EarningsRateID' => null
          'RatePerUnit' => null
          'NumberOfUnits' => null
          'FixedAmount' => null
```

Additionally, I bumped into https://github.com/calcinai/xero-php/pull/705 when debugging. What is the bug it's trying to resolve? The XML looks like it is correctly pluralized:
```xml
<EarningsLines>
    <EarningsLine>
        <EarningsRateID>2f1b01ea-4118-48ee-b4b1-a49432c42c24</EarningsRateID>
        <RatePerUnit>100.000000</RatePerUnit>
        <NumberOfUnits>20.0000</NumberOfUnits>
    </EarningsLine>
</EarningsLines>
```
as `::singularize('EarningsLines')` will be `EarningsLine` which matches the XML.

**Comment by Healyhatman** [comment] 2020-04-08 11:01
#705 fixed TimesheetEarningsLines, which are separate to EarningsLines

As to everything else you said I have no idea what any of that means but I'll certainly give it a try

**Comment by Josh-G** [comment] 2020-04-08 11:25
Sorry you're right, I mean TimesheetEarningsLines not EarningsLines but the same applies? They singularize the same way.

What about them did #705 fix?

**Comment by Healyhatman** [comment] 2020-04-08 11:30
Before the fix, it was not correctly parsing TimesheetEarningsLines. It was just getting the first EarningsLine from TimesheetEarningsLines and setting that as the full property if that makes sense.

The  "parent" is called <TimesheetEarningsLines> and it contains multiple <EarningsLine>, as opposed to <EarningsLines> which contain <EarningLine>.

So
```
<TimesheetEarningsLine>
   <EarningsLine>
      ... properties ....
   </EarningsLine
<TimesheetEarningsLine>
```

 as opposed to EarningsLines which is 

```
<EarningsLines>
   <EarningsLine>
      ... properties ...
   </EarningsLine>
</EarningsLines>
```

**Comment by Josh-G** [comment] 2020-04-08 11:35
Ah, I understand now thanks :) The same problem will also affect `LeaveEarningsLines` as well then.

**Comment by Healyhatman** [comment] 2020-04-08 11:39
I haven't had to access LeaveEarningsLines yet :) If you can think of a better way than tacking on to my fix in 705 by all means

**Comment by Healyhatman** [comment] 2020-04-13 23:20
@calcinai can you please have a look at his suggested fix I don't understand what's happening

**Comment by calcinai** [comment] 2020-04-13 23:27
@Healyhatman looking...

**Comment by calcinai** [comment] 2020-04-13 23:28
@Josh-G I think what you're proposing makes sense, would you be able to make a PR against master and I'll do some testing?

**Comment by Josh-G** [comment] 2020-04-14 08:20
Thanks for taking the time @calcinai, I've created #722 as a draft. I will add a couple of unit tests after work before marking it as ready for review.

**Closed** 2020-04-27 20:43 UTC
