### ISSUE TITLE
Error saving SalesDetails and PurchaseDetails in ..\Accounting\Item 

### ISSUE THREAD

**Issue by dot5enko** [calcinai/xero-php#126] opened 2016-01-28 08:16 UTC
when calling addSalesDetail on Item object it should assign one element the $this->_data['SalesDetails'] instead of adding element to Remote\Collection();

**Comment by calcinai** [comment] 2016-01-28 21:49
Hey, I've had a very quick look at this.  It looks like this is a special case, where the name of there XML tags aren't consistent with what's in them.  I'll try to get it going tonight.

**Comment by calcinai** [comment] 2016-02-05 21:46
This is actually a duplicate of #81, I'll try to sort them both out.

**Comment by dot5enko** [comment] 2016-02-09 15:27
ok

**Closed** 2016-02-27 08:32 UTC
Labels: duplicate
