### ISSUE TITLE
Updating/Archiving Tracking Category Options

### ISSUE THREAD

**Issue by tysonarmstrong** [calcinai/xero-php#637] opened 2019-09-19 21:53 UTC
Hi,

I'm trying to archive a large number of tracking category options. It appears it isn't possible to save() the TrackingOption object directly, so I've also tried updating the parent Tracking Category options collection with the updated option (ie. setting Status to ARCHIVED). When I try to save this Tracking Category I get a 404. 
The endpoint it's posting to is:
https://api.xero.com/api.xro/2.0/TrackingCategories/{TrackingCategoryID}/Options/
which is giving the 404.

The API docs say that you can update a Tracking Option directly at:
https://api.xero.com/api.xro/2.0/TrackingCategories/{TrackingCategoryID}/Options/{TrackingOptionID}
but the TrackingOption class has no supported methods.
(https://developer.xero.com/documentation/api/tracking-categories)

Am I messing this up somewhere, or is it not supported by this API client?

Cheers,
Tyson

**Comment by kgdiem** [comment] 2019-09-25 05:31
Duplicate of #256 

Same here

**Closed** 2020-02-06 19:41 UTC
