### ISSUE TITLE
Tracking category option not creating  

### ISSUE THREAD

**Issue by codeclouds-team** [calcinai/xero-php#584] opened 2019-06-10 05:06 UTC
Hi, I am trying to create a tracking category and few options for that category. But I am failed to attach tracking options to the category.

**Steps:** 

* creating a tracking category bt `XeroPHP\Models\Accounting\TrackingCategory` model.
* Saving Xero id for that category.
* Creating an instance of `XeroPHP\Models\Accounting\TrackingCategory\TrackingOption` 
* At the of attaching options, adding saved Xero category id, and push options to the instance by `addOption` method.
* Saving them.

**Result:** 
* Options are not saving to Xero.

**Comment by gkavaliu** [comment] 2019-07-06 21:06
I did some testing and I believe this is because

TrackingOption is not an endpoint in Xero it is actually Option

PUT https://api.xero.com/api.xro/2.0/TrackingCategories/{TrackingCategoryID}/Options

**Comment by nelwa** [comment] 2019-09-17 07:12
Any update on this?  I'm getting the same problem...

**Comment by calcinai** [comment] 2020-02-09 19:36
Duplicate of #256

**Closed by calcinai** 2020-02-09 19:36 UTC
