### ISSUE TITLE
Set Bank Account Number

### ISSUE THREAD

**Issue by iveoles** [calcinai/xero-php#116] opened 2015-11-27 11:32 UTC
There's no method to set a Bank Account Number on the Account model. I added it manually and it correctly adds this to Xero as a bank account. 

It's my understanding that this is generated from the documentation, so I'm unsure how I would go about adding this in a Pull Request

In my local Account model this code is working as expected

```php
    /**
     * @param string $value
     * @return Account
     */
    public function setBankAccountNumber($value) {
        $this->propertyUpdated('BankAccountNumber', $value);
        $this->_data['BankAccountNumber'] = $value;
        return $this;

    }
```

**Comment by calcinai** [comment] 2015-11-27 19:47
Hey, this is a duplicate of #106, I'll do a release to update this fro you.

**Closed** 2015-11-27 19:53 UTC
